--
-- PostgreSQL database dump
--

SET client_encoding = 'SQL_ASCII';
SET standard_conforming_strings = off;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET escape_string_warning = off;

--
-- Name: artefact; Type: DATABASE; Schema: -; Owner: artefact
--

-- CREATE DATABASE artefact WITH TEMPLATE = template0 ENCODING = 'SQL_ASCII';


-- ALTER DATABASE artefact OWNER TO artefact;

\connect artefact

SET client_encoding = 'SQL_ASCII';
SET standard_conforming_strings = off;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET escape_string_warning = off;

SET search_path = public, pg_catalog;

SET default_tablespace = '';

SET default_with_oids = true;

--
-- Name: data; Type: TABLE; Schema: public; Owner: artefact; Tablespace: 
--

CREATE TABLE data (
    data_uid character varying(255),
    device_type character varying(255),
    device_id character varying(255),
    class character varying(255),
    "timestamp" character varying(255),
    location character varying(255),
    filename character varying(255),
    file_length character varying(255)
);


ALTER TABLE public.data OWNER TO artefact;

--
-- Name: patient; Type: TABLE; Schema: public; Owner: artefact; Tablespace: 
--

CREATE TABLE patient (
    cpr character varying(255),
    operator character varying(255),
    uid character varying(255)
);


ALTER TABLE public.patient OWNER TO artefact;

--
-- Name: public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM postgres;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- PostgreSQL database dump complete
--

