#!/bin/bash

TEST=`echo -n $1 | cut -d'.' -f1`
OUTPUT=test_$TEST
LUAFILE=$TEST.lua

SCRIPTDIR=`dirname $0`

echo -e "\033[0;2mTesting $TEST:"
echo Testing $TEST: > $OUTPUT.log

	echo -n "* Running   $TEST test"
	echo Running $TEST test: >> $OUTPUT.log
	if ./test_lua $LUAFILE >> $OUTPUT.log 2>&1; then
	        echo -e "\r\t\t\t\t\t\t[\033[1;32mSuccess\033[0;2m]"
		echo "[Success]" >> $OUTPUT.log
	else
		echo -e "\r\t\t\t\t\t\t[\033[1;31mFailure\033[0;2m]"
		echo "[Failure]" >> $OUTPUT.log
		rm -f $OUTPUT
	fi

echo
